export const PAUSED = Symbol.for('STREAMIE EVENT: PAUSED');
export const ITEM_PUSHED = Symbol.for('STREAMIE EVENT: ITEM PUSHED');
export const CONCURRENT_CAPACITY_REACHED = Symbol.for('STREAMIE EVENT: CONCURRENT CAPACITY REACHED');
export const CONCURRENT_CAPACITY_RELIEVED = Symbol.for('STREAMIE EVENT: CONCURRENT CAPACITY RELIEVED');
